# guestbook-app/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook-app
  labels:
    app.kubernetes.io/name: guestbook-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: guestbook-app
    app.kubernetes.io/instance: {{ .Release.Name }}
